{% set version = "v0.3.1" %}
{% set checksum = "06171471d2de99a3cc89d0004caf6128cd2dc39904d28cef95ba1acf1a563d23" %}
{% set version_formatted = version|replace("v","") %}
{% set pytorch_flavor = pytorch_flavor or "pytorch" %}
{% set torchvision_flavor = torchvision_flavor or "torchvision" %}
{% set package_name = package_name or "inferno" %}


package:
    name: {{ package_name }}
    version: {{ version_formatted }}

source:
    url: https://github.com/inferno-pytorch/inferno/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
    number: 3
    script: python -m pip install --no-deps --ignore-installed .
    noarch: python

requirements:
    host:
        - python >=3.6
        - pip
        - pytest-runner

    run:
        - python >=3.6
        - pyyaml
        - scipy
        - scikit-image
        - h5py
        - dill
        - networkx
        - tensorboardx >=1.4
        - {{ pytorch_flavor }} {{ pytorch_pinning }}
        - {{ torchvision_flavor }} {{ torchvision_pinning }}

test:
    imports:
        - inferno

about:
    license: Apache 2.0
    license_file: LICENSE
    license_family: APACHE
    summary: A utility library around PyTorch
    home: https://github.com/inferno-pytorch/inferno

extra:
    recipe-maintainers:
        - constantinpape
        - nasimrahaman
